framework:
    workflows:
        invoice_payment:
            supports:
                - 'App\Entity\Invoice'
            marking_store:
                type: method
                property: paymentState
            places:
                - required
                - pending
                - aborted
                - paid
                - failed
            transitions:
                submit_request:
                    from: required
                    to: pending
                abort:
                    from: required
                    to: aborted
                pay:
                    from: pending
                    to: paid
                fail:
                    from: pending
                    to: failed